### ISSUE TITLE
Add new serval-dna client commands to serval-dna plugin

### ISSUE THREAD

**Issue by dismantl** [opentechinstitute/commotiond#97]
This requires adding the new commands to serval-client.c to match those in serval-dna's commandline.c

**Comment by jheretic** [comment]
I believe this is complete, correct @dismantl?

**Comment by dismantl** [comment]
I think there are still some missing since we upgraded to the latest version of serval-dna, but I also don't think it's a big deal if we're eventually moving away from running serval-dna as a plugin for commotiond.

**Comment by jheretic** [comment]
Closing this as no longer relevant.
